"""0.2 schem compress.

Revision ID: d26c2878f9d7
Revises:
Create Date: 2025-03-16 14:14:27.853735

"""

from __future__ import annotations

from typing import TYPE_CHECKING

import sqlalchemy as sa

from alembic import op
from mxr.orm import MXRDB

if TYPE_CHECKING:
    from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "a540c124bbcc"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

schema = MXRDB.schema_name


def upgrade() -> None:
    """Upgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "drinks",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("preparation", sa.String(), nullable=False),
        sa.Column("alcohol_content", sa.Float(), nullable=True),
        sa.Column("data_source", sa.String(), nullable=True),
        sa.Column("drink_type", sa.String(), nullable=True),
        sa.Column("garnish", sa.String(), nullable=True),
        sa.Column("glass", sa.String(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema=schema,
    )
    op.create_table(
        "ingredients",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("alcohol_content", sa.Float(), nullable=True),
        sa.Column("category", sa.String(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        schema=schema,
    )
    op.create_table(
        "drink_ingredient_associations",
        sa.Column("drinks_id", sa.Integer(), nullable=False),
        sa.Column("ingredients_id", sa.Integer(), nullable=False),
        sa.Column("measurement", sa.String(length=50), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["drinks_id"],
            ["richie_mxr.drinks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["ingredients_id"],
            ["richie_mxr.ingredients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("drinks_id", "ingredients_id"),
        schema=schema,
    )
    op.create_index("drinks_id", "drink_ingredient_associations", ["drinks_id"], unique=False, schema=schema)
    op.create_index("ingredients_id", "drink_ingredient_associations", ["ingredients_id"], unique=False, schema=schema)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ingredients_id", table_name="drink_ingredient_associations", schema=schema)
    op.drop_index("drinks_id", table_name="drink_ingredient_associations", schema=schema)
    op.drop_table("drink_ingredient_associations", schema=schema)
    op.drop_table("ingredients", schema=schema)
    op.drop_table("drinks", schema=schema)
    # ### end Alembic commands ###
